### ISSUE TITLE
Missing language in the support list

### ISSUE THREAD

**Issue by Aetheridon** [engineer-man/emkc#124]

**Comment by HexF** [comment]
JavaScript (ECMAScript) is a language with no "official" implementation, however one of the most implementations of the language is `node`, which is listed in the languages list, along with `deno` - a newer javascript runtime (although still based on V8).
In terms of piston, this means that while javascript would be more correct to use in a list of languages, the execution framework needs to be specified because `deno != node`, and while they both execute javascript, they have different APIs available.
see: https://github.com/engineer-man/piston/blob/8cc1f6c2b5250679c2ee26b3ea9ffb736726ddd3/config/languages.json#L146

**Comment by LewisScript** [comment]
Yes i'm aware node is on the list, but both can be executed, so i just thought adding javascript might avoid confusion
