### ISSUE TITLE
create 10 hard challenges

### ISSUE THREAD

**Issue by realtux** [engineer-man/emkc#22]

**Comment by kalix123** [comment]
1. Given two strings, write a program that efficiently finds the longest common subsequence
2. Write a function that combines two lists by alternatingly taking elements. For example: given the two lists [a, b, c] and [1, 2, 3], the function should return [a, 1, b, 2, c, 3].
3. Write a function that given a list of non negative integers, arranges them such that they form the largest possible number. For example, given [50, 2, 1, 9], the largest formed number is 95021.
ok. that's all I got for now. I'll get back to you when I think of some other ones. probably soon. I just have to walk my dog.

**Comment by sggts04** [comment]
Jimmy and Ryan have two strings S1 and S2 respectively of equal length. Jimmy will win the game if any of the permutations of his string become equal to Ryan's string. Print whether Jimmy is winning or not.

**Comment by Nova-Ardent** [comment]
(sorry meant for hard not medium) Write a program to generate the calculated output of a strings in prefix, postfix, and infix form. The strings may contain, addition, subtraction, multiplication, division and carets (exponents)
Example for input
+ 1 6
1 8 + 
1 + 3

Output:
7
9
4

**Comment by Nova-Ardent** [comment]
given a maze of 1's and 0's example:
`
111111101
100010001
101010101
111000111
100010001
111010101
111111101
`
determine if the maze is solvable, and if it is mark the `shortest` path with 2's, otherwise print the original maze.
input:
`
111111101
100010001
101010101
111000111
100010001
111010101
111111101
`

output
`
111111121
100012221
101012101
111002111
100012221
111010121
111111121
`
